<script setup>
import { onMounted, ref, watch } from 'vue'
import AdminLayout from '../../components/admin/AdminLayout.vue'
import { adminFetch, adminJson } from '../../services/adminAuth'

const tab=ref('pending'),search=ref(''),loading=ref(false),rows=ref([]),error=ref(''),notice=ref('')
const review=ref(null),reviewLoading=ref(false),actionLoading=ref(false),verificationNote=ref(''),rejectionReason=ref(''),showReject=ref(false)
const tabs=[['all','সব অনুদান'],['pending','অপেক্ষমাণ'],['confirmed','নিশ্চিত'],['rejected','প্রত্যাখ্যাত']]

async function load(){loading.value=true;error.value='';const params=new URLSearchParams;if(tab.value!=='all')params.set('status',tab.value);if(search.value)params.set('search',search.value);try{const response=await adminFetch(`/api/admin/donations?${params}`);if(!response.ok)throw new Error();rows.value=(await response.json()).data}catch{error.value='অনুদানের তথ্য লোড করা যায়নি।'}finally{loading.value=false}}
async function openReview(item){reviewLoading.value=true;error.value='';try{review.value=await adminJson(`/api/admin/donations/${item.id}`);verificationNote.value=review.value.verification_note||'';rejectionReason.value='';showReject.value=false}catch(e){error.value=e.message}finally{reviewLoading.value=false}}
function closeReview(){if(actionLoading.value)return;review.value=null;showReject.value=false}
async function confirmDonation(){if(!confirm('এই দানটি নিশ্চিত করলে এটি মোট হিসাবে যুক্ত হবে এবং রসিদ পাওয়া যাবে। নিশ্চিত করবেন?'))return;actionLoading.value=true;try{const data=await adminJson(`/api/admin/donations/${review.value.id}/confirm`,{method:'POST',body:JSON.stringify({verification_note:verificationNote.value})});notice.value=data.message;review.value=null;showReject.value=false;await load()}catch(e){error.value=e.message}finally{actionLoading.value=false}}
async function rejectDonation(){if(!rejectionReason.value.trim()){error.value='প্রত্যাখ্যানের কারণ লিখুন।';return}actionLoading.value=true;try{const data=await adminJson(`/api/admin/donations/${review.value.id}/reject`,{method:'POST',body:JSON.stringify({verification_note:verificationNote.value,rejection_reason:rejectionReason.value})});notice.value=data.message;review.value=null;showReject.value=false;await load()}catch(e){error.value=e.message}finally{actionLoading.value=false}}
watch(tab,load);onMounted(load)
</script>

<template><AdminLayout><div class="admin-title"><div><p>অনুদান ব্যবস্থাপনা</p><h1>অনুদানসমূহ</h1></div></div><p v-if="notice" class="success-message">{{notice}}</p><section class="panel"><div class="filter-bar"><div class="tabs"><button v-for="item in tabs" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]">{{item[1]}}</button></div><form class="filter-inputs" @submit.prevent="load"><input v-model.trim="search" placeholder="নাম, মোবাইল বা রসিদ খুঁজুন"><button>খুঁজুন</button></form></div><p v-if="error" class="login-error">{{error}}</p><div class="table-wrap"><table><thead><tr><th>রসিদ নম্বর</th><th>দাতা</th><th>পরিমাণ</th><th>উদ্দেশ্য</th><th>পদ্ধতি</th><th>অবস্থা</th><th></th></tr></thead><tbody><tr v-if="loading"><td colspan="7"><div class="empty compact">তথ্য লোড হচ্ছে…</div></td></tr><tr v-else-if="!rows.length"><td colspan="7"><div class="empty compact"><span>◷</span><b>কোনো অনুদানের তথ্য নেই</b><p>জনসাধারণের দানের তথ্য এখানে দেখা যাবে।</p></div></td></tr><tr v-for="item in rows" v-else :key="item.id"><td><b>{{item.receipt_number}}</b></td><td>{{item.donor_name}}<small class="table-sub">{{item.mobile}}</small></td><td>৳ {{Number(item.amount).toLocaleString('bn-BD')}}</td><td>{{item.purpose?.name_bn}}</td><td>{{item.payment_method}}</td><td><span class="status-pill" :class="item.status">{{item.status==='pending'?'অপেক্ষমাণ':item.status==='confirmed'?'নিশ্চিত':'প্রত্যাখ্যাত'}}</span></td><td><button class="review-button" @click="openReview(item)">{{item.status==='pending'?'পর্যালোচনা':'বিস্তারিত'}}</button></td></tr></tbody></table></div></section><section class="review-guide"><span>✓</span><div><b>যাচাইকরণ প্রক্রিয়া</b><p>পেমেন্ট প্রমাণ পরীক্ষা করে দান নিশ্চিত বা প্রত্যাখ্যান করুন। নিশ্চিত দানই কেবল মোট হিসাব ও রসিদে অন্তর্ভুক্ত হবে।</p></div></section>

<div v-if="review||reviewLoading" class="review-modal" @click.self="closeReview"><section class="review-dialog"><header><div><p>অনুদান যাচাইকরণ</p><h2>{{review?.receipt_number||'লোড হচ্ছে…'}}</h2></div><button @click="closeReview">✕</button></header><div v-if="review" class="review-body"><div class="review-columns"><section><h3>দাতার তথ্য</h3><dl><dt>নাম</dt><dd>{{review.donor_name}}</dd><dt>মোবাইল</dt><dd>{{review.mobile}}</dd></dl></section><section><h3>দানের তথ্য</h3><dl><dt>পরিমাণ</dt><dd class="amount">৳ {{Number(review.amount).toLocaleString('bn-BD')}}</dd><dt>উদ্দেশ্য</dt><dd>{{review.purpose?.name_bn}}</dd><dt>জমার তারিখ</dt><dd>{{new Date(review.submitted_at).toLocaleString('bn-BD')}}</dd></dl></section></div><section class="payment-review"><h3>পেমেন্ট তথ্য</h3><dl><dt>পদ্ধতি</dt><dd>{{review.payment_method}}</dd><dt v-if="review.transaction_id">Transaction ID</dt><dd v-if="review.transaction_id"><code>{{review.transaction_id}}</code></dd><dt v-if="review.bank_account">ব্যাংক</dt><dd v-if="review.bank_account">{{review.bank_account.bank_name}} · {{review.bank_account.account_number}}</dd></dl><a v-if="review.payment_screenshot_path" class="proof-link" :href="`/api/admin/donations/${review.id}/screenshot`" target="_blank">পেমেন্ট প্রমাণ দেখুন ↗</a><p v-else class="no-proof">কোনো স্ক্রিনশট জমা দেওয়া হয়নি।</p></section><label>যাচাইকরণ নোট<textarea v-model="verificationNote" rows="3" placeholder="ঐচ্ছিক অভ্যন্তরীণ নোট"></textarea></label><template v-if="review.status==='pending'"><div v-if="showReject" class="reject-box"><label>প্রত্যাখ্যানের কারণ<textarea v-model="rejectionReason" rows="3" required placeholder="কেন যাচাই করা যায়নি তা লিখুন"></textarea></label></div><div class="review-actions"><button v-if="!showReject" class="reject-action" @click="showReject=true">✕ প্রত্যাখ্যান করুন</button><button v-else class="secondary-button" @click="showReject=false">বাতিল</button><button v-if="showReject" class="reject-confirm" :disabled="actionLoading" @click="rejectDonation">প্রত্যাখ্যান নিশ্চিত করুন</button><button v-else class="confirm-action" :disabled="actionLoading" @click="confirmDonation">✓ দান নিশ্চিত করুন</button></div></template><div v-else class="final-status" :class="review.status"><b>{{review.status==='confirmed'?'এই দান নিশ্চিত করা হয়েছে':'এই দান প্রত্যাখ্যান করা হয়েছে'}}</b><p v-if="review.rejection_reason">{{review.rejection_reason}}</p></div></div></section></div>
  </AdminLayout></template>
