<script setup>
import { onMounted, reactive, ref } from 'vue'
import AdminLayout from '../../components/admin/AdminLayout.vue'
import { adminFetch, adminJson } from '../../services/adminAuth'

const rows = ref([]), editing = ref(null), file = ref(null), preview = ref(null), error = ref(''), saving = ref(false)
const form = reactive({ title_bn: '', title_en: '', display_order: 0, is_active: true })
async function load() { rows.value = await adminJson('/api/admin/gallery') }
function reset() { editing.value = null; file.value = null; preview.value = null; error.value = ''; Object.assign(form, { title_bn: '', title_en: '', display_order: 0, is_active: true }) }
function choose(event) { file.value = event.target.files?.[0] ?? null; preview.value = file.value ? URL.createObjectURL(file.value) : null }
function edit(item) { editing.value = item; file.value = null; preview.value = null; Object.assign(form, { title_bn: item.title_bn ?? '', title_en: item.title_en ?? '', display_order: item.display_order, is_active: item.is_active }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function save() { error.value = ''; if (!editing.value && !file.value) { error.value = 'একটি ছবি নির্বাচন করুন।'; return }; saving.value = true; const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, typeof value === 'boolean' ? (value ? '1' : '0') : value)); if (file.value) data.append('image', file.value); try { const response = await adminFetch(editing.value ? `/api/admin/gallery/${editing.value.id}` : '/api/admin/gallery', { method: 'POST', body: data }); const json = await response.json(); if (!response.ok) throw new Error(Object.values(json.errors ?? {}).flat()[0] ?? json.message); reset(); await load() } catch (e) { error.value = e.message } finally { saving.value = false } }
async function remove(item) { if (confirm('ছবিটি স্থায়ীভাবে মুছে ফেলবেন?')) { await adminJson(`/api/admin/gallery/${item.id}`, { method: 'DELETE' }); await load() } }
onMounted(load)
</script>

<template><AdminLayout><div class="admin-title"><div><p>হোমপেজ ব্যবস্থাপনা</p><h1>ছবির গ্যালারি</h1></div></div><div class="gallery-admin-grid"><section class="panel"><div class="panel-head"><div><h2>{{ editing ? 'ছবি সম্পাদনা' : 'নতুন ছবি যোগ করুন' }}</h2><p>ছবিগুলো হোমপেজের গ্যালারিতে দেখা যাবে</p></div></div><form class="management-form" @submit.prevent="save"><label>ছবির শিরোনাম (বাংলা)<input v-model="form.title_bn" placeholder="যেমন: বুদ্ধ পূর্ণিমা আয়োজন"></label><label>ছবির শিরোনাম (ইংরেজি)<input v-model="form.title_en"></label><label>ছবি নির্বাচন<input type="file" accept="image/png,image/jpeg,image/webp" :required="!editing" @change="choose"></label><img v-if="preview || editing?.image_url" class="gallery-preview" :src="preview || editing.image_url" alt="Gallery preview"><div class="two-inputs"><label>ক্রম<input v-model.number="form.display_order" type="number" min="0" required></label><label class="toggle-label"><input v-model="form.is_active" type="checkbox"> হোমপেজে প্রকাশ করুন</label></div><p v-if="error" class="login-error">{{ error }}</p><button class="admin-button" :disabled="saving">{{ saving ? 'সংরক্ষণ হচ্ছে…' : 'সংরক্ষণ করুন' }}</button><button v-if="editing" type="button" class="secondary-button" @click="reset">বাতিল</button></form></section><section class="panel"><div class="panel-head"><div><h2>গ্যালারির ছবি</h2><p>{{ rows.length }}টি ছবি</p></div></div><div class="gallery-list"><article v-for="item in rows" :key="item.id"><img :src="item.image_url" :alt="item.title_bn"><div><b>{{ item.title_bn || 'শিরোনাম নেই' }}</b><small>ক্রম: {{ item.display_order }} · {{ item.is_active ? 'প্রকাশিত' : 'বন্ধ' }}</small><button @click="edit(item)">সম্পাদনা</button><button class="danger-text" @click="remove(item)">মুছুন</button></div></article><div v-if="!rows.length" class="empty compact">এখনো কোনো ছবি যোগ করা হয়নি।</div></div></section></div></AdminLayout></template>

<style scoped>.gallery-admin-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.9fr);gap:20px}.gallery-preview{width:100%;height:230px;object-fit:cover;border-radius:8px;border:1px solid #e1e7e1}.gallery-list article{display:flex;gap:12px;padding:12px 0;border-bottom:1px solid #edf0ec}.gallery-list img{width:115px;height:80px;object-fit:cover;border-radius:7px}.gallery-list b,.gallery-list small{display:block}.gallery-list small{margin:4px 0;color:#849087;font-size:10px}.gallery-list button{margin-right:8px;padding:0;border:0;background:none;color:#35634e;font:inherit;font-size:10px;cursor:pointer}@media(max-width:950px){.gallery-admin-grid{grid-template-columns:1fr}}</style>
